console.log("Hail, Mary, full of grace,")
console.log("the Lord is with thee.")
console.log("Blessed art thou amongst women")
console.log("and blessed is the fruit of thy womb, Jesus.")
console.log("Holy Mary, Mother of God,")
console.log("pray for us sinners,")
console.log("now and at the hour of our death.")
console.log("Amen.")